id: PC9BF44FB
initial_creation_type: input
source_metadata:
  Title: Mahāyāna-sūtra-saṃgrahaḥ ( part 1)
  Editor: Vaidya, P.L
  Publisher: The Mithila Institute of Post-Graduate Studies and Research in Sanskrit
    Learning
  Place of Publication: Darbhanga
  Year: '1961'
  Śālistambasūtram:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:06:40.859922'
last_modified_at: '2022-03-08T16:06:40.859930'
